spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/LostPetHelperDB
    username: postgres
    password: "240919"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect